default_stages: ["commit"]
repos:
-   repo: local
    hooks:
    -   id: lintr
        name: lintr
        description: check if a .R file is lint free (using lintr)
        entry: inst/bin/lintr
        language: script
        files: '\.[rR]$'
