language: r
# dist: bionic # Uncomment until fix of https://travis-ci.community/t/r-install-broken-travis-ci-rstudio-org-returns-403/9640
cache: packages

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice

script:
  - travis_wait 60 R CMD build .
  - travis_wait 60 R CMD check *tar.gz
  # Break when style is incorrect
  - Rscript -e 'lintr::expect_lint_free()'

after_success:
  # lintr-bot is mild
  #- Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - # No local files created
  - if [[ $(egrep -R "\"~" --include={*.R,*.Rmd}) ]]; then echo "Local file created"; exit 1; fi;

after_failure:
