language: r
cache: packages

r_packages:
  - devtools

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice

script:
  # Do the actual build
  - travis_wait 60 R CMD build .
  - travis_wait 60 R CMD check *tar.gz
  # Break when style is incorrect
  - R CMD INSTALL *tar.gz
  - Rscript -e "lintr::expect_lint_free()"

after_success:
  # lintr-bot is mild
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - # No local files created
  - if [[ $(egrep -R "\"~" --include={*.R,*.Rmd}) ]]; then echo "Local file created"; exit 1; fi;

after_failure:
